project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # 
  page-footer: "Made with Quarto"
  navbar:
    left:
      - text: Proyectos
        href: projects/index.qmd
        target: "_blank"
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/axel-alexander-pereda-escalante/
        target: "_blank"
      - icon: github
        href: https://github.com/AlexanderPereda
        target: "_blank" 
format:
  html:
    mainfont: "roboto"
    theme:
      light: minimal
      dark: darkly

